### ISSUE TITLE
Rolling from a macro does not work if a target is selected

### ISSUE THREAD

**Issue by wrycu** [wrycu/StarWarsFFG-Enhancements#202]
```js
animation.js:300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'actor')
    at attack_animation (animation.js:300:111)
    at 🎁game.ffg.RollFFG.prototype.toMessage#ffg-star-wars-enhancements (ffg-star-wars-enhancements.js:164:24)
    at async HTMLButtonElement.<anonymous> (roll-builder.js:194:9)
```

**Comment by wrycu** [comment]
This is a bug in the base system. I've fixed it, and it'll be released in 1.901.
