### ISSUE TITLE
LibWrapper throws "Can't wrap 'Combat.prototype.createEmbeddedEntity', target does not exist or could not be found."

### ISSUE THREAD

**Issue by Zamrod** [wrycu/StarWarsFFG-Enhancements#98]
On startup in a new world I get the following error:

```
A: Error detected in module FFG Star Wars Enhancements. It is likely this module has not been updated for FVTT Version 9.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/wrycu/StarWarsFFG-Enhancements

Ask the community for support:
- FoundryVTT Discord's #modules-troubleshooting channel: https://discord.gg/foundryvtt
- FoundryVTT Reddit: https://www.reddit.com/r/FoundryVTT

== Technical Details:
Detected by libWrapper.
Package ID= ffg-star-wars-enhancements
Error= libWrapper: Can't wrap 'Combat.prototype.createEmbeddedEntity', target does not exist or could not be found.

[Detected 1 package: ffg-star-wars-enhancements]
    at new 🎁constructor (http://50.70.246.20:30001/modules/lib-wrapper/lib-wrapper.js:1:26139)
    at http://50.70.246.20:30001/modules/lib-wrapper/lib-wrapper.js:1:43436
    at ce (http://50.70.246.20:30001/modules/lib-wrapper/lib-wrapper.js:1:43469)
    at Function.🎁register [as register] (http://50.70.246.20:30001/modules/lib-wrapper/lib-wrapper.js:1:46573)
    at register_hooks (http://50.70.246.20:30001/modules/ffg-star-wars-enhancements/ffg-star-wars-enhancements.js:176:16)
    at http://50.70.246.20:30001/modules/ffg-star-wars-enhancements/ffg-star-wars-enhancements.js:106:5
    at Function._call (http://50.70.246.20:30001/scripts/foundry.js:294:14)
    at Function.callAll (http://50.70.246.20:30001/scripts/foundry.js:253:12)
    at Game.setupGame (http://50.70.246.20:30001/scripts/foundry.js:5547:11)
    at async Game._initializeGameView (http://50.70.246.20:30001/scripts/foundry.js:6479:5)
    at async Game.initialize (http://50.70.246.20:30001/scripts/foundry.js:5415:5)
onError @ foundry.js:316
```

**Comment by wrycu** [comment]
What version module, system, and Foundry are you using?

**Comment by Zamrod** [comment]
Looks like I was stuck on an old version that wouldn't update. Uninstalled and reinstalled. It works now. Sorry.

**Comment by Italemyae** [comment]
Same issue here with the last update. 
Resolved by uninstall / reinstall module. This closed ticket was helpfull, thanks for it.
